# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField(blank=True, default=0)),
                ('total_cost', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
