# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-04 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0008_auto_20180331_1535'),
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_count', models.IntegerField(blank=True, default=0, null=True)),
                ('viand_count', models.IntegerField(blank=True, default=0, null=True)),
                ('meals_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_profiling.Student')),
            ],
            options={
                'verbose_name_plural': 'Item Tallies',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_price', models.IntegerField(blank=True, default=0, null=True)),
                ('viand_price', models.IntegerField(blank=True, default=0, null=True)),
                ('meals_price', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
