# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='purchase',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Consumable'),
        ),
    ]
