# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0006_auto_20180226_1036'),
        ('canteen', '0002_auto_20180226_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_profiling.Student'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_profiling.Teacher'),
        ),
    ]
