# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20180315_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
