# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfractions',
            name='date_incurred',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
