# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0002_auto_20180221_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfractions',
            name='date_incurred',
        ),
        migrations.AlterField(
            model_name='studentinfractions',
            name='reason',
            field=models.CharField(default='ashkj', max_length=300),
            preserve_default=False,
        ),
    ]
