# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0003_auto_20180331_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('1', '7-Diamond'), ('2', '7-Gold'), ('3', '7-Pearl'), ('4', '8-Dahlia'), ('5', '8-Kamia'), ('6', '8-Rosal'), ('7', '9-Calcium'), ('8', '9-Lithium'), ('9', '9-Sodium'), ('10', '10-Electron'), ('11', '10-Neutron'), ('12', '10-Proton'), ('13', '11-Curie'), ('14', '11-Darwin'), ('15', '11-Einstein'), ('16', '11-Franklin'), ('17', '11-Newton'), ('18', '12-Farad'), ('19', '12-Hertz'), ('20', '12-Kelvin'), ('21', '12-Pascal'), ('22', '12-Tesla')], default=None, max_length=13, null=True),
        ),
    ]
