# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0003_auto_20180221_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfractions',
            name='date_filed',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfractions',
            name='date_incurred',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
