# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0004_auto_20180221_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfractions',
            name='infraction',
            field=models.CharField(blank=True, choices=[('CC', 'Cutting_Class'), ('T', 'Tardy'), ('A', 'Absence')], default=None, max_length=13, null=True),
        ),
    ]
