# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0004_auto_20180331_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.IntegerField(blank=0, null=True),
        ),
    ]
