# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_profiling', '0005_studentinfractions_infraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfractions',
            name='infraction',
            field=models.CharField(blank=True, choices=[('CC', 'Cutting Class'), ('T', 'Tardy'), ('A', 'Absence')], default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfractions',
            name='infraction',
            field=models.CharField(choices=[('CC', 'Cutting Class'), ('T', 'Tardy'), ('A', 'Absence')], default=None, max_length=13),
        ),
    ]
